SportyWebApp/SportyWebApp/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportyWebApp.Models
{
    public class EventViewModel
    {
        public int Id { get; set; }
        public int MaxPlayers { get; set; }
        public int FreePlayers { get; set; }
        public DateTime StartTime { get; set; }
        public string Location { get; set; }
        public CityViewModel City { get; set; }
        public int SportId { get; set; }
        public string SportName { get; set; }
        public UserViewModel Creator { get; set; }
        public List<UserViewModel> Participants {get; set;}

    }
}

SportyWebApp/SportyWebApp/Controllers/EventsController.cs
using SportyWebApp.Models;
using SportyWebApp.WebAPI;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Reflection;

namespace SportyWebApp.Controllers
{
    public class EventsController : Controller
    {

        API api = new API();
        List<SportViewModel> allSports = new List<SportViewModel>();
        List<EventListModel> searchEvents = new List<EventListModel>();

        [HttpGet]
        public ActionResult Subscribe(int id)
        {
            return PartialView("_Subscribe", id);
        }
        // GET: Search
        public async Task<ActionResult> Search(string sportId, string date, string cityName, string freePlayers)
        {                      
            UserViewModel userViewModel = (UserViewModel) Session["UserViewModel"];
            if (userViewModel == null) return RedirectToAction("Login", "User");

            allSports = await api.HttpGetAllSports(); 

            // First request
            if (sportId == null)
            {
                ViewBag.CityEntered = true;
                ViewBag.AllSports = allSports;
                ViewBag.SearchEvents = searchEvents;
                ViewBag.CurrentPage = "SearchEventPage";
                return View();
            }
            
            // Search request
            if (cityName == "")
            {
                ViewBag.CityEntered = false;
                ViewBag.AllSports = allSports;
                ViewBag.SearchEvents = searchEvents;
                ViewBag.CurrentPage = "SearchEventPage";
                return View();
            }

            ViewBag.CityEntered = true;
            searchEvents = await api.HttpFindEvents(sportId, date, cityName, freePlayers);
            foreach (var entry in searchEvents)
            {
                var sportName = entry.SportName;
                if (!String.IsNullOrEmpty(sportName))
                {
                    sportName = sportName.First().ToString().ToUpper() + sportName.Substring(1);
                    entry.SportName = sportName;
                }
            }

            int resultsDivIDHeight = searchEvents.Count * 200;
            if (resultsDivIDHeight < 400) resultsDivIDHeight = 500;
            int findMaindDivHeight = 250 + resultsDivIDHeight;


            ViewBag.CurrentPage = "SearchEventPage";
            ViewBag.AllSports = allSports;
            ViewBag.SearchEvents = searchEvents;
            ViewBag.CityName = cityName;
            return View();
        }
        
        public async Task<ActionResult> FutureEvents()
        {
            UserViewModel userViewModel = (UserViewModel)Session["UserViewModel"];
            if (userViewModel == null) return RedirectToAction("Login", "User");

            string username = ((UserViewModel)Session["UserViewModel"]).UserName;
            string url = HttpContext.Request.Url.AbsoluteUri;
            int index = url.LastIndexOf('/');
            string time = url.Substring(index+1);

            List<EventListModel> events = await api.HttpGetEvents(username, time.ToLower());
            ViewBag.FutureEvents = events;
            ViewBag.MainTitle = "Moji događaji";
            return View((UserViewModel)Session["UserViewModel"]);
        }

        public async Task<ActionResult> PastEvents()
        {
            UserViewModel userViewModel = (UserViewModel)Session["UserViewModel"];
            if (userViewModel == null) return RedirectToAction("Login", "User");

            string username = ((UserViewModel)Session["UserViewModel"]).UserName;
            string url = HttpContext.Request.Url.AbsoluteUri;
            int index = url.LastIndexOf('/');
            string time = url.Substring(index + 1);

            List<EventListModel> events = await api.HttpGetEvents(username, time.ToLower());
            ViewBag.PastEvents = events;
            ViewBag.MainTitle = "Moji događaji";
            return View((UserViewModel)Session["UserViewModel"]);
        }

        // GET: Event/Details/5
        public async Task<ActionResult> Details(int id)
        {
            UserViewModel userViewModel = (UserViewModel)Session["UserViewModel"];
            if (userViewModel == null) return RedirectToAction("Login", "User");

            EventDetailsModel model = await api.HttpGetEvent(id);
            bool isPlayer = false;
            string username = ((UserViewModel)Session["UserViewModel"]).UserName;
            int count = model.lstUsers.Where(e => e.UserName == username).Count();
            if (count > 0)
                isPlayer = true;
            ViewBag.isPlayer = isPlayer;
            ViewBag.users = model.lstUsers;
            ViewBag.MainTitle = "Pregled događaja";
            return View(model);
        }

        // GET: Event/Create
        public async Task<ActionResult> Create()
        {
            UserViewModel userViewModel = (UserViewModel)Session["UserViewModel"];
            if (userViewModel == null) return RedirectToAction("Login", "User");

            List<SportViewModel> lst = await api.HttpGetAllSports();
            EventCreateModel model = new EventCreateModel();
            model.lstSports = lst;
            ViewBag.MainTitle = "Novi dagađaj";
            return View(model);
        }

        // POST: Event/Create
        [HttpPost]
        public async Task<ActionResult> Create(EventCreateModel model)
        {
            UserViewModel userViewModel = (UserViewModel)Session["UserViewModel"];
            if (userViewModel == null) return RedirectToAction("Login", "User");

            int hours = -1, minutes = -1;
            string[] time = model.Time.Split(':');
            if (!time[0].Equals("0") && !time[0].Equals("00"))
            {
                Int32.TryParse(time[0], out hours);
            }
            if (!time[1].Equals("0") && !time[1].Equals("00"))
            {
                Int32.TryParse(time[1], out minutes);
            }
            if (minutes == 0 || hours == 0)
            {
                List<SportViewModel> lst = await api.HttpGetAllSports();
                model.lstSports = lst;
                ViewBag.MainTitle = "Novi dagađaj";
                ViewBag.Message = "Unesite ispravno vrijeme";
                return View(model);
            }
            if (hours == -1)
                hours = 0;
            if (minutes == -1)
                minutes = 0;
            TimeSpan ts = new TimeSpan(hours, minutes, 0);
            model.Date = model.Date.Date + ts;
            model.UserName = ((UserViewModel)Session["UserViewModel"]).UserName;
            try
            {
                string response = await api.HttpCreateEvent(model);
                if (response.Equals("OK"))
                {
                    return RedirectToAction("FutureEvents");
                }
                else
                {
                    ViewBag.poruka = response;
                    List<SportViewModel> lst = await api.HttpGetAllSports();
                    model.lstSports = lst;
                    ViewBag.MainTitle = "Novi dagađaj";
                    ViewBag.Message = response;
                    return View(model);
                }
            }
            catch
            {
                List<SportViewModel> lst = await api.HttpGetAllSports();
                ViewBag.MainTitle = "Novi dagađaj";
                model.lstSports = lst;
                ViewBag.Message = "Nemoguće izvršiti akciju";
                return View(model);
            }
        }

        // GET: Event/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Event/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Event/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Event/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public class RequireRequestValueAttribute : ActionMethodSelectorAttribute
        {
            public RequireRequestValueAttribute(string valueName)
            {
                if (valueName == null)
                {
                    ValueName = "";
                }
                else
                {
                    ValueName = valueName;
                }         
            }
            public override bool IsValidForRequest(ControllerContext controllerContext, MethodInfo methodInfo)
            {
                return (controllerContext.HttpContext.Request[ValueName] != null);
            }

            public string ValueName { get; private set; }
        }

    }

}

SportyWebApp/SportyWebApp/Controllers/SubscriptionController.cs
using SportyWebApp.Models;
using SportyWebApp.WebAPI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace SportyWebApp.Controllers
{
    public class SubscriptionController : Controller
    {
        API api = new API();
        [HttpPost]
        public async Task<ActionResult> GetSubscriptionEvents(int SubId)
        {
            ViewBag.lstEvents = await api.HttpGetSubscriptionEvents(SubId);
            //obrisat
            string username = ((UserViewModel)Session["UserViewModel"]).UserName;
            List<EventListModel> events = await api.HttpGetEvents(username, "a");
            ViewBag.lstEvents = events;



            Subscription model = new Subscription();
            model.UserName = ((UserViewModel)Session["UserViewModel"]).UserName;
            ViewBag.lstSubscriptions = await api.HttpGetUserSubscriptions(((UserViewModel)(Session["UserViewModel"])).UserName);
            ViewBag.lstSports = await api.HttpGetAllSports();
            ViewBag.lstSubscriptions = await api.HttpGetUserSubscriptions(model.UserName);
            //obrisat
            ViewBag.lstSubscriptions = new List<Subscription>() { new Subscription() { Id = 1, Name = "Sub1" }, new Subscription() { Id = 2, Name = "Sub2" } };
            return View("Home", model);
        }

        // GET: Subscription/Create
        public async Task<ActionResult> Home()
        {
            Subscription model = new Subscription();
            model.UserName = ((UserViewModel)Session["UserViewModel"]).UserName;
            ViewBag.lstSubscriptions = await api.HttpGetUserSubscriptions(((UserViewModel)(Session["UserViewModel"])).UserName);
            ViewBag.lstSports = await api.HttpGetAllSports();
            ViewBag.lstSubscriptions = await api.HttpGetUserSubscriptions(model.UserName);
            ViewBag.lstSubscriptions = new List<Subscription>() { new Subscription() { Id = 1, Name = "Sub1" }, new Subscription() { Id = 2, Name = "Sub2" }};
            return View(model);
        }

        // POST: Subscription/Create
        [HttpPost]
        public async Task<ActionResult> Create([Bind(Include = "UserName,SportId,CityName,Name")] Subscription model)
        {
            string response = await api.HttpCreateSubscription(model);
            if (response.Equals("OK"))
            {
                return RedirectToAction("Home");
            }
            else
            {
                model = new Subscription();
                model.UserName = ((UserViewModel)Session["UserViewModel"]).UserName;
                ViewBag.lstSubscriptions = await api.HttpGetUserSubscriptions(((UserViewModel)(Session["UserViewModel"])).UserName);
                ViewBag.lstSports = await api.HttpGetAllSports();
                ViewBag.lstSubscriptions = await api.HttpGetUserSubscriptions(model.UserName);
                ViewBag.lstSubscriptions = new List<Subscription>() { new Subscription() { Id = 1, Name = "Sub1" }, new Subscription() { Id = 2, Name = "Sub2" } };
                ViewBag.error = response;
                return View("Home", model);
            }
        }

        // GET: Subscription/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Subscription/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Subscription/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Subscription/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SportyWebApp/SportyWebApp/Views/Shared/_Event.cshtml
@model SportyWebApp.Models.EventListModel
@{var filledSeats = Model.MaxPlayers - Model.FreePlayers; }

<section class="sportCard">
    <div class="iconDiv">
        @if (Model.SportName == "Mali nogomet")
        {
            <img src="~/Images/footballBall.png" class="sportBallIcon" />
        }
        else if (Model.SportName == "Rukomet")
        {
            <img src="~/Images/handballBall.png" class="sportBallIcon" />
        }
        else if (Model.SportName == "Košarka")
        {
            <img src="~/Images/basketballBall.png" class="sportBallIcon" />
        }
        else if (Model.SportName == "Badminton")
        {
            <img src="~/Images/badmintonBall.png" class="sportBallIcon" />
        }
        else if (Model.SportName == "Tenis")
        {
            <img src="~/Images/tennisRacket.png" class="sportBallIcon" />
        }
    </div>
    <div class="descriptionDiv">
        <label id="descriptionText" style="margin-left: 0%;">
            @Model.SportName
            @Model.Location, @Model.CityName
            Broj prijavljenih igrača: @filledSeats/@Model.MaxPlayers
            @Model.StartTime
        </label>
    </div>
    <div class="buttonsDiv">
        <button class="buttonCheckIn btn btn-info" onclick="subsribeEventShowModal(this)" data-id="@Model.Id">PRIJAVA</button>
        <button class="buttonDetails btn btn-secondary" onclick="">DETALJI</button>
    </div>
</section>

SportyWebApp/SportyWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/simpleSidebar.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/search.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/shared.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/profile.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/register.css" rel="stylesheet"  type="text/css" />
    <link href="~/Content/home.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/subscribe.css" rel="stylesheet" type="text/css" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <h1 id="logoTitle">Sporty</h1>
    <div><ul id="navUl"><li class="navLi"></li></ul></div>
    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <button id="menu-toggle">
                <img src="~/Images/hamburgerMenuIcon.png" id="menu-toggle-image" />
            </button>
            <ul class="sidebar-nav">
                <li>@Html.ActionLink("Moji događaji", "FutureEvents", "Events") </li>
                <li>@Html.ActionLink("Novi događaj", "Create", "Events") </li>
                <li>@Html.ActionLink("Traži događaje", "Search", "Events")</li>
                @if (ViewBag.CurrentPage != "HomePage")
                {
                  <li>@Html.ActionLink("Danas u gradu", "Index", "Home")</li>
                }
                <li>@Html.ActionLink("Pretplate", "Home", "Subscription") </li>
                <li>@Html.ActionLink("Postavke profila", "Edit", "Profile")</li>
                <li>@Html.ActionLink("Odjava", "Login", "User")</li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div id="container-fluid" class="container-fluid">
                <div class="row">
                    <div id="col-lg-12" class="col-lg-12">
                        @RenderBody()
                    </div>
                </div>
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Sporty development</p>
                </footer>
            </div>
        </div>
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function (e) {
            $("#menu-toggle").blur();
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
    @Scripts.Render("~/Scripts/jquery-3.3.1.js")
    @Scripts.Render("~/Scripts/layout.js")
    @Scripts.Render("~/Scripts/event.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SportyWebApp/SportyWebApp/Views/Shared/_PastEvent.cshtml
@model SportyWebApp.Models.EventListModel
@{var filledSeats = Model.MaxPlayers - Model.FreePlayers; }

<head>
    <link href="~/Content/pastEvents.css" rel="stylesheet" type="text/css">
    <meta charset="UTF-8">
</head>

<section class="sportCard">
    <div class="iconDiv">
        @if (Model.SportName == "Mali nogomet")
        {
            <img src="~/Images/footballBall.png" class="sportBallIcon" />
        }
        else if (Model.SportName == "Rukomet")
        {
            <img src="~/Images/handballBall.png" class="sportBallIcon" />
        }
        else if (Model.SportName == "Košarka")
        {
            <img src="~/Images/basketballBall.png" class="sportBallIcon" />
        }
        else if (Model.SportName == "Badminton")
        {
            <img src="~/Images/badmintonBall.png" class="sportBallIcon" />
        }
        else if (Model.SportName == "Tenis")
        {
            <img src="~/Images/tennisRacket.png" class="sportBallIcon" />
        }
    </div>
    <div class="descriptionDiv">
        <label id="descriptionText" style="margin-left: 0%;">
            @Model.SportName
            @Model.Location, @Model.CityName
            Broj prijavljenih igrača: @filledSeats/@Model.MaxPlayers
            @Model.StartTime
        </label>
    </div>
    <div class="buttonsDiv">
        <button class="buttonDetails btn btn-secondary" onclick="redirectToDetails(@Model.Id)">DETALJI</button>
    </div>
</section>

SportyWebApp/SportyWebApp/Views/Shared/_Subscribe.cshtml
<div id='myModal' class='modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'>
                <div class="modal-body">
                    <p>
                        Jeste li sigurni da se želite prijaviti?
                    </p>
                </div>
                <div class="modal-footer">
                    <button id="submitButton" class="btn btn-primary" onclick="subscribeButtonClicked">Da</button>
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Ne</button>
                </div>
            </div>
        </div>
    </div>

</div>   

<script>

    function subscribeButtonClicked() {
        // TODO: Subscribe to API
    }

</script>